### ISSUE TITLE
Create a simple Watermark-Component for Demo

### ISSUE THREAD

**Issue by Equindar** [Equindar/LunarEclipse#23]
A watermark needs to be applied to content, marking it as content with subject of change.

**Comment by Equindar** [comment]
Example: https://stackoverflow.com/questions/21458162/creating-watermark-using-html-and-css

**Comment by tusharwebd** [comment]
Hi Equindar! I would like to work on this issue. Can you share where we need to add this watermark? Also any developer guides I can refer to setup the application for this project?

**Comment by Equindar** [comment]
Thanks for your interest @tusharwebd, sadly the water mark is a low priority issue right now.
Maybe we come up with our own solution, but as a dev you dont want to reinvent the wheel, we will prolly use this one: https://github.com/uiwjs/react-watermark

i will work on an install section in the readme - good point there.
